import { Divider } from "antd";
import Head from "next/head";
import FilmPoster from "../components/film-poster";
import FilmSlider from "../components/film-slider";
import HeaderSlider from "../components/slider";


export default function Home() {  


  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div>
        <HeaderSlider />
        <Divider orientation="right">برترین فیلم ها</Divider>
        <FilmSlider />
        <Divider orientation="right">بدترین فیلم ها</Divider>
        <FilmSlider dark />
        <FilmPoster />
        <Divider orientation="right">کم بازدید ترین فیلم ها</Divider>
        <FilmSlider />

      </div>
    </div>
  );
}

export async function getServerSideProps(context) {
  

  return {
    props: {
      
    },
  };
}
